#############################################################################
# Makefile for building: viewfsmanager
# Generated by qmake (2.01a) (Qt 4.6.3) on: Tue Jan 31 00:08:36 2012
# Project:  viewfsmanager.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile viewfsmanager.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		managerwindow.cpp \
		mountdialog.cpp moc_managerwindow.cpp \
		moc_mountdialog.cpp
OBJECTS       = main.o \
		managerwindow.o \
		mountdialog.o \
		moc_managerwindow.o \
		moc_mountdialog.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		viewfsmanager.pro
QMAKE_TARGET  = viewfsmanager
DESTDIR       = 
TARGET        = viewfsmanager

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_managerwindow.h ui_mountdialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: viewfsmanager.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile viewfsmanager.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile viewfsmanager.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/viewfsmanager1.0.0 || $(MKDIR) .tmp/viewfsmanager1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/viewfsmanager1.0.0/ && $(COPY_FILE) --parents managerwindow.h mountdialog.h .tmp/viewfsmanager1.0.0/ && $(COPY_FILE) --parents main.cpp managerwindow.cpp mountdialog.cpp .tmp/viewfsmanager1.0.0/ && $(COPY_FILE) --parents managerwindow.ui mountdialog.ui .tmp/viewfsmanager1.0.0/ && (cd `dirname .tmp/viewfsmanager1.0.0` && $(TAR) viewfsmanager1.0.0.tar viewfsmanager1.0.0 && $(COMPRESS) viewfsmanager1.0.0.tar) && $(MOVE) `dirname .tmp/viewfsmanager1.0.0`/viewfsmanager1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/viewfsmanager1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_managerwindow.cpp moc_mountdialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_managerwindow.cpp moc_mountdialog.cpp
moc_managerwindow.cpp: managerwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) managerwindow.h -o moc_managerwindow.cpp

moc_mountdialog.cpp: mountdialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mountdialog.h -o moc_mountdialog.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_managerwindow.h ui_mountdialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_managerwindow.h ui_mountdialog.h
ui_managerwindow.h: managerwindow.ui
	/usr/bin/uic-qt4 managerwindow.ui -o ui_managerwindow.h

ui_mountdialog.h: mountdialog.ui
	/usr/bin/uic-qt4 mountdialog.ui -o ui_mountdialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp managerwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

managerwindow.o: managerwindow.cpp managerwindow.h \
		ui_managerwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o managerwindow.o managerwindow.cpp

mountdialog.o: mountdialog.cpp mountdialog.h \
		ui_mountdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mountdialog.o mountdialog.cpp

moc_managerwindow.o: moc_managerwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_managerwindow.o moc_managerwindow.cpp

moc_mountdialog.o: moc_mountdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mountdialog.o moc_mountdialog.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

